# Generated by Django 5.1.1 on 2024-09-28 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance_tracker.basemodel')),
                ('name', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('theme', models.CharField(choices=[('purple', 'Purple'), ('turquoise', 'Turquoise'), ('brown', 'Brown'), ('magenta', 'Magenta'), ('blue', 'Blue'), ('grey', 'Grey'), ('army_green', 'Army Green'), ('gold', 'Gold'), ('orange', 'Orange')], default='purple', max_length=20)),
            ],
            bases=('finance_tracker.basemodel',),
        ),
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance_tracker.basemodel')),
                ('name', models.CharField(max_length=128)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('theme', models.CharField(choices=[('purple', 'Purple'), ('turquoise', 'Turquoise'), ('brown', 'Brown'), ('magenta', 'Magenta'), ('blue', 'Blue'), ('grey', 'Grey'), ('army_green', 'Army Green'), ('gold', 'Gold'), ('orange', 'Orange')], default='purple', max_length=20)),
            ],
            bases=('finance_tracker.basemodel',),
        ),
        migrations.CreateModel(
            name='RecurringBill',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance_tracker.basemodel')),
                ('name', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], default='M', max_length=1)),
                ('next_due_date', models.DateField()),
                ('theme', models.CharField(choices=[('purple', 'Purple'), ('turquoise', 'Turquoise'), ('brown', 'Brown'), ('magenta', 'Magenta'), ('blue', 'Blue'), ('grey', 'Grey'), ('army_green', 'Army Green'), ('gold', 'Gold'), ('orange', 'Orange')], default='purple', max_length=20)),
                ('icon', models.CharField(choices=[('arrow', 'Arrow'), ('birds', 'Birds'), ('bread', 'Bread'), ('circle-dot', 'Circle Dot'), ('cloud', 'Cloud'), ('easel', 'Easel'), ('egg', 'Egg'), ('film', 'Film'), ('hex', 'Hex'), ('radar', 'Radar'), ('spoon', 'Spoon'), ('stairs', 'Stairs'), ('steering-wheel', 'Steering Wheel'), ('string', 'String'), ('triangle', 'Triangle')], default='arrow', max_length=20)),
            ],
            bases=('finance_tracker.basemodel',),
        ),
    ]
